server:
  port: 0
spring:
  application:
    name: message-service
  data:
    mongodb:
      database: message-service
      port: 27017
      host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka